# Generated by Django 2.2.4 on 2019-09-16 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('todas', models.BooleanField(default=False)),
                ('categoria', models.ManyToManyField(blank=True, to='data.Categoria')),
                ('oferta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.Oferta')),
            ],
        ),
    ]
