# Generated by Django 2.2.4 on 2019-09-16 21:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_descuento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descuento',
            options={'verbose_name': 'Descuento', 'verbose_name_plural': 'Descuentos'},
        ),
        migrations.AlterField(
            model_name='descuento',
            name='categoria',
            field=models.ManyToManyField(blank=True, help_text='Categorías a la que se aplicaran el descuento.', to='data.Categoria'),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor del porcentaje.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='todas',
            field=models.BooleanField(default=False, help_text='Seleccionar si el descuento es sobre todas las categorías.'),
        ),
    ]
