# Generated by Django 2.2.4 on 2019-09-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_auto_20190916_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineaoferta',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
