# Generated by Django 2.2.4 on 2019-09-16 21:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_auto_20190916_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineaoferta',
            name='costo_custom',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
