# Generated by Django 2.2.4 on 2019-09-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0006_auto_20190916_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Tasa de cambio'),
        ),
    ]
