# Generated by Django 2.2 on 2020-08-24 16:24

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses', models.PositiveIntegerField(default=0, unique=True, verbose_name='Meses de financiación')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='TipoVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('directa', models.BooleanField(default=False, help_text='Marcar si el tipo es directa.')),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Moneda')),
            ],
            options={
                'verbose_name': 'Tipo de venta',
                'verbose_name_plural': 'Tipos de venta',
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('empleados', models.PositiveIntegerField(default=50, help_text='Cantidad de empleados. Indicar un valor entre 1 y 2000.', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(2000)], verbose_name='Empleados')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.Plan')),
                ('tipo_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.TipoVenta')),
                ('usuario', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.CreateModel(
            name='EscalaPrecio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimo', models.PositiveIntegerField(default=0, help_text='Mínimo en tipo de venta y plan.', verbose_name='Cantidad mínima')),
                ('alcance', models.PositiveIntegerField(default=0, verbose_name='Cantidad máxima')),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, help_text='"b" en f(x) = mx + b', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio base')),
                ('tp_unidad', models.DecimalField(decimal_places=4, default=0, help_text='"m" en f(x) = mx + b', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='TP Unidad')),
                ('descuento_terceros', models.DecimalField(decimal_places=2, default=0, help_text='Descuento sin el signo %. Ej. 135,5 (%)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.Plan')),
                ('tipos_de_venta', models.ManyToManyField(blank=True, to='saas.TipoVenta')),
            ],
            options={
                'verbose_name': 'Escala de Precio',
                'verbose_name_plural': 'Escalas de Precios',
            },
        ),
    ]
