# Generated by Django 2.2.10 on 2020-02-19 20:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financing', models.CharField(choices=[('36', '36 meses'), ('48', '48 meses')], help_text='Meses de financiación.', max_length=2)),
                ('hardware', models.CharField(choices=[('p', 'Propio'), ('t', 'Terceros')], help_text='Utilizará hardware propio (SPEC) o de terceros?', max_length=1)),
                ('tipo_venta', models.CharField(choices=[('0', 'Venta directa'), ('1', 'Distribuidor'), ('2', 'Integrador')], help_text='Quién efectúa la venta?', max_length=1)),
                ('comision', models.DecimalField(decimal_places=2, default=0, help_text='Múltiplo de la comisión', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Comision')),
            ],
            options={
                'verbose_name': 'Comision',
                'verbose_name_plural': 'Comisiones',
            },
        ),
    ]
