# Generated by Django 2.2.10 on 2020-02-21 21:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_comision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloSaaS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Módulo SaaS',
                'verbose_name_plural': 'Módulos SaaS',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='empleados',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de empleados'),
        ),
        migrations.AddField(
            model_name='offer',
            name='financing',
            field=models.CharField(choices=[('36', '36 meses'), ('48', '48 meses')], default='36', help_text='Meses de financiación.', max_length=2, verbose_name='Financiación'),
        ),
        migrations.AddField(
            model_name='offer',
            name='hardware',
            field=models.CharField(choices=[('p', 'Propio'), ('t', 'Terceros')], default='p', help_text='Utilizará hardware propio (SPEC) o de terceros?', max_length=1),
        ),
        migrations.AddField(
            model_name='offer',
            name='tipo_venta',
            field=models.CharField(choices=[('0', 'Venta directa'), ('1', 'Distribuidor'), ('2', 'Integrador')], default='0', help_text='Quién efectúa la venta?', max_length=1, verbose_name='Tipo de venta'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Múltiplo de la comisión', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Comisión'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='financing',
            field=models.CharField(choices=[('36', '36 meses'), ('48', '48 meses')], default='36', help_text='Meses de financiación.', max_length=2, verbose_name='Financiación'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='hardware',
            field=models.CharField(choices=[('p', 'Propio'), ('t', 'Terceros')], default='p', help_text='Utilizará hardware propio (SPEC) o de terceros?', max_length=1),
        ),
        migrations.AlterField(
            model_name='comision',
            name='tipo_venta',
            field=models.CharField(choices=[('0', 'Venta directa'), ('1', 'Distribuidor'), ('2', 'Integrador')], default='0', help_text='Quién efectúa la venta?', max_length=1, verbose_name='Tipo de venta'),
        ),
        migrations.CreateModel(
            name='EscalaTransferPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, help_text='Máximo de escala anterior (si existe).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio base')),
                ('alcance', models.PositiveIntegerField(default=0, unique=True, verbose_name='Cantidad máxima')),
                ('tp_unidad', models.DecimalField(decimal_places=2, default=0, help_text='Transfer Price por unidad adicional -o total-.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='TP Unidad')),
                ('precio_total', models.BooleanField(default=False)),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.ModuloSaaS')),
            ],
            options={
                'verbose_name': 'Escala de Transfer Price',
                'verbose_name_plural': 'Escalas de Transfer Price',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='modulos',
            field=models.ManyToManyField(blank=True, to='saas.ModuloSaaS'),
        ),
    ]
