# Generated by Django 2.2.10 on 2020-02-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0003_auto_20200221_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalatransferprice',
            name='alcance',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad máxima'),
        ),
        migrations.AlterField(
            model_name='escalatransferprice',
            name='precio_total',
            field=models.BooleanField(default=False, help_text='Seleccionar si el precio no depende de la cantidad.'),
        ),
    ]
