# Generated by Django 2.2.10 on 2020-02-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0004_auto_20200221_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalatransferprice',
            name='precio_total',
        ),
        migrations.AddField(
            model_name='modulosaas',
            name='precio_diff_unidad',
            field=models.BooleanField(default=False, help_text='El precio no tiene "diferencial" por unidad. Puede tener rangos.', verbose_name='Diferencial x Unidad'),
        ),
    ]
