# Generated by Django 2.2.10 on 2020-02-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0005_auto_20200221_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulosaas',
            name='precio_diff_unidad',
        ),
        migrations.AddField(
            model_name='modulosaas',
            name='pricing_management',
            field=models.CharField(choices=[('0', 'Valor fijo por módulo'), ('1', 'Rangos de precio'), ('2', 'Variable por cantidad')], default='0', help_text='Cómo se maneja el pricing del módulo?', max_length=1, verbose_name='Pricing management'),
        ),
    ]
