# Generated by Django 2.2.10 on 2020-02-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0006_auto_20200221_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulosaas',
            name='pricing_management',
            field=models.CharField(choices=[('vf', 'Valor fijo por módulo'), ('rp', 'Rangos de precio'), ('pu', 'Variable por cantidad')], default='vf', help_text='Cómo se maneja el pricing del módulo?', max_length=2, verbose_name='Pricing management'),
        ),
    ]
