# Generated by Django 2.2.10 on 2020-02-22 00:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0007_auto_20200221_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Margin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financing', models.CharField(choices=[('36', '36 meses'), ('48', '48 meses')], default='36', help_text='Meses de financiación.', max_length=2, verbose_name='Financiación')),
                ('hardware', models.CharField(choices=[('p', 'Propio'), ('t', 'Terceros')], default='p', help_text='Utilizará hardware propio (SPEC) o de terceros?', max_length=1)),
                ('tipo_venta', models.CharField(choices=[('0', 'Venta directa'), ('1', 'Distribuidor'), ('2', 'Integrador')], default='0', help_text='Quién efectúa la venta?', max_length=1, verbose_name='Tipo de venta')),
                ('margin_spec', models.DecimalField(decimal_places=2, default=0, help_text='Múltiplo del márgen', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Margen SPEC')),
                ('margin_integrador', models.DecimalField(decimal_places=2, default=0, help_text='Múltiplo del márgen', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Margen Integrador')),
                ('margin_mayorista', models.DecimalField(decimal_places=2, default=0, help_text='Múltiplo del márgen', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Margen Mayorista')),
                ('rebate', models.DecimalField(decimal_places=2, default=0, help_text='Múltiplo del rebate', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Rebate')),
            ],
            options={
                'verbose_name': 'Margen & Rebate',
                'verbose_name_plural': 'Márgenes & Rebates',
            },
        ),
        migrations.DeleteModel(
            name='Comision',
        ),
    ]
