# Generated by Django 2.2.10 on 2020-02-26 15:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0008_auto_20200221_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='margin',
            name='rebate',
        ),
        migrations.AddField(
            model_name='margin',
            name='rebate_mayorista',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Múltiplo del rebate', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Rebate Mayorista'),
        ),
        migrations.AddField(
            model_name='margin',
            name='rebate_partner',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Múltiplo del rebate', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Rebate Partner'),
        ),
        migrations.AlterField(
            model_name='margin',
            name='hardware',
            field=models.CharField(choices=[('p', 'SPEC'), ('t', 'Terceros')], default='p', help_text='Utilizará hardware propio (SPEC) o de terceros?', max_length=1),
        ),
        migrations.AlterField(
            model_name='margin',
            name='margin_integrador',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Múltiplo del márgen', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Margen Integrador'),
        ),
        migrations.AlterField(
            model_name='margin',
            name='margin_mayorista',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Múltiplo del márgen', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Margen Mayorista'),
        ),
        migrations.AlterField(
            model_name='margin',
            name='tipo_venta',
            field=models.CharField(choices=[('0', 'End User'), ('1', 'Integrador'), ('2', 'Mayorista')], default='0', help_text='Quién efectúa la venta?', max_length=1, verbose_name='Tipo de venta'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='financing',
            field=models.CharField(choices=[('36', '36 meses'), ('48', '48 meses')], default='36', help_text='Meses de financiación.', max_length=2, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='hardware',
            field=models.CharField(choices=[('p', 'SPEC'), ('t', 'Terceros')], default='p', help_text='Utilizará hardware propio (SPEC) o de terceros?', max_length=1),
        ),
        migrations.AlterField(
            model_name='offer',
            name='tipo_venta',
            field=models.CharField(choices=[('0', 'End User'), ('1', 'Integrador'), ('2', 'Mayorista')], default='0', help_text='Quién efectúa la venta?', max_length=1, verbose_name='Tipo de venta'),
        ),
    ]
