# Generated by Django 2.2.10 on 2020-02-26 15:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0009_auto_20200226_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='margin',
            name='margin_integrador',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Múltiplo del márgen', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Margen Partner'),
        ),
    ]
