# Generated by Django 2.2.4 on 2020-01-03 01:00

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title_font', models.CharField(blank=True, default='Segoe UI Black', max_length=30, verbose_name='Fuente de títulos')),
                ('report_subtitle_font', models.CharField(blank=True, default='Segoe UI Black', max_length=30, verbose_name='Fuente de subtítulos')),
                ('report_body_font', models.CharField(blank=True, default='Segoe UI', max_length=30, verbose_name='Fuente de cuerpo')),
                ('report_color_title', colorful.fields.RGBColorField(default='#000', verbose_name='Color de títulos')),
                ('report_bg_title', colorful.fields.RGBColorField(default='#000', verbose_name='Color de fondo de títuos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
