# Generated by Django 2.2.4 on 2020-01-03 01:20

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='report_bg_title',
            field=colorful.fields.RGBColorField(default='#FF0000', verbose_name='Color de fondo de títuos'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='report_color_title',
            field=colorful.fields.RGBColorField(default='#FF0000', verbose_name='Color de títulos'),
        ),
    ]
